### ISSUE TITLE
What copyright restrictions (if any) exist on sounds and images?

### ISSUE THREAD

**Issue by laserlemon** [collectiveidea/fireside#39]
See: https://github.com/collectiveidea/fireside/tree/master/public/sounds
and: https://github.com/collectiveidea/fireside/tree/master/public/images

**Comment by laserlemon** [comment]
From Campfire email support:

> The campfire sounds, and the gifs/images that accompany them, aren’t licensable. They’re like the memes that are widely used around the internet, in that they’re created purely for entertainment purposes. We're not really the ones to ask for licensing.

**Comment by laserlemon** [comment]
Does this clear us to use these assets and license the application under MIT? /cc @danielmorrison

**Comment by danielmorrison** [comment]
That comment says they're unlicensable. That doesn't give us the right to relicense them under MIT. 

I know I'm probably being overly cautious. It sounds like what [Steve Klabnik went through with emoji](http://words.steveklabnik.com/emoji-licensing).

Not knowing who owns the copyright isn't excuse. Do I think anyone will come after us? No, but is it the Right thing? Not really. 

I dunno, if 37s aren't upset that's the best thing, but still doesn't give us the right to relicense. 

Anyone else have thoughts?

**Comment by ersatzryan** [comment]
We could leave them out of the repo and build a way to upload them and put other custom sounds. Then we could have documentation that talks about where campfire stores theirs and what they are called...

**Comment by ersatzryan** [comment]
Since the way the API sends the info to the clients and how they accept messages to to decided if it is a `/play` message it shouldn't be too hard and should still work with the clients

**Comment by ersatzryan** [comment]
We could also build a script to bootstrap it with the campfire ones... that way the user could determine if they want to or not and we aren't trying to relicense something MIT

**Comment by laserlemon** [comment]
:+1: :point_up:

We could add a database table for sounds:

| name | url | message |
| :-- | :-- | :-- |
| tmyk | https://123.campfirenow.com/sounds/tmyk.mp3 | :sparkles: :star: The More You Know :sparkles: :star: |
| nyan | https://123.campfirenow.com/sounds/nyan.mp3 | https://123.campfirenow.com/images/nyan.gif |

Could we have a rake task for seeding the table with default sounds without violating copyright?
